# Foot base config (Omarchy-wired)
# Dynamic theme colors are loaded from Omarchy current theme output.
include=~/.config/omarchy/current/theme/foot.ini

font=Hack Nerd Font:size=13.5
pad=14x14

[colors-dark]
# alpha=1.0
alpha-mode = all

[cursor]
style=block
blink=no

[key-bindings]
primary-paste=Shift+Insert
clipboard-copy=Control+Insert
